### ISSUE TITLE
[Bug] CustomLauncherRewrite-*.jar wildcard to launch the game inside run.sh doesn't work 

### ISSUE THREAD

**Issue by RiQuY** [hyperdefined/CustomLauncherRewrite#100]
**Describe the issue**
When running the run.sh script it tries to open the file CustomLauncherRewrite-*.jar instead of replacing the * symbol with the version number.

Contents of my `/opt/CustomLauncherRewrite/` folder:
```
ls /opt/CustomLauncherRewrite/
CustomLauncherRewrite-1.9.1.jar  run.sh
```

**Screenshot/video/etc**

**Log file**
Output of `/opt/CustomLauncherRewrite/run.sh`
```
ls: no se puede acceder a 'CustomLauncherRewrite-*.jar': No existe el fichero o el directorio
Error: Unable to access jarfile 
```
Translation: Cannot access 'CustomLauncherRewrite-*.jar': File or folder doesn't exists.

**UPDATE**: The issue also happens with sudo and without the wildcard *, specifying the exact filename.
```
sudo /opt/CustomLauncherRewrite/run.sh
[sudo] contraseña para root: 
ls: no se puede acceder a 'CustomLauncherRewrite-1.9.1.jar': No existe el fichero o el directorio
Error: Unable to access jarfile 
```

**Comment by RiQuY** [comment]
I was able to fix the launching error by changing the line `latest=$(ls -t CustomLauncherRewrite-*.jar | head -n1)` to this:
- `latest=$(ls -t $(dirname "$0")/CustomLauncherRewrite-1.9.1.jar | head -n1)`

But now the Java program crashes with this error:
- https://gist.github.com/RiQuY/938ce10b0f188e19f6f342d8ec9cc54c

**Comment by hyperdefined** [comment]
Interesting, I'll take a look shortly.

**Comment by hyperdefined** [comment]
I would remove all files from the launcher, then run the installer again. I believe I have fixed all your issues you were facing.
