### ISSUE TITLE
[Bug] - Desktop path in uninstaller is not using $(xdg-user-dir DESKTOP) and prompt asking to keep files doesn't appear

### ISSUE THREAD

**Issue by RiQuY** [hyperdefined/CustomLauncherRewrite#101]
**Describe the issue**
The uninstaller is missing the $(xdg-user-dir DESKTOP) logic introduced in the installer to handle creation/deletion of the desktop shorcut for CustomLauncherRewrite. And the propmt asking to keep or remove ttr_files doesn't appear.

**Log file**
Uninstaller log:
```
curl -s https://raw.githubusercontent.com/hyperdefined/CustomLauncherRewrite/master/linux/uninstaller.sh | bash
Removing /opt/CustomLauncherRewrite...
Removing the desktop entry...
rm: no se puede borrar '/home/ricardo/Desktop/customlauncherrewrite.desktop': No existe el fichero o el directorio
CustomLauncherRewrite has been uninstalled!
```
Translation: rm cannot delete '........' folder or file doesn't exists.

**PD**: Thank you for fixing the other issues, now the launcher installs and run without errors.

**Comment by hyperdefined** [comment]
Thank you for the report, I'll take a look shortly. Glad the installer works now for you!

I didn't give the linux part of the program the love it needs.

**Comment by hyperdefined** [comment]
I would do a complete wipe again of the launcher and reinstall it, I changed a lot on the Linux installer. This should be the final fix for everything.
