### ISSUE TITLE
[Bug] Cannot update TTR

### ISSUE THREAD

**Issue by ahmouse15** [hyperdefined/CustomLauncherRewrite#116]
The TTR patch manifest URL was changed from 
`https://cdn.toontownrewritten.com/content/patchmanifest` to
`https://cdn.toontownrewritten.com/content/patchmanifest.txt`

Rather, the second URL has been around for a while, but the former was just (intentionally?) removed and also happens to be what CLR uses, so at the moment patch manifests cannot be retrieved.

In fact, CLR should listen to the `manifest` field that's sent alongside the play cookie, which provides the patch manifest URL as described [here](https://github.com/ToontownRewritten/api-doc/blob/master/login.md#non-queued-response)

**Comment by hyperdefined** [comment]
CLR already loads the manifest from the login response (see https://github.com/hyperdefined/CustomLauncherRewrite/blob/master/src/main/java/lol/hyper/customlauncher/login/LoginHandler.java#L117).

I just tried launching the game myself, and got this response back:
```
{cookie=xxx, success=true, manifest=/content/patchmanifest, gameserver=45.77.79.152}
```
CLR sees the manifest and appends it to `https://cdn.toontownrewritten.com` as the API docs state. It seems like this is not a CLR problem but a TTR issue.

**Comment by ahmouse15** [comment]
Oh very interesting. Since its the API's fault, I tried the official launcher to see if it would fail as well, but it worked just fine which is odd. After some digging it seems their launcher hardcodes the URL with `patchmanifest.txt`, ignoring the `manifest` field completely! 

So, the API and their docs are misaligned again. I'll open a bug on their repo, hopefully it's fixed quickly like last time.

**Comment by ahmouse15** [comment]
Fixed. See https://github.com/ToontownRewritten/api-doc/issues/24
