### ISSUE TITLE
[Bug] run.sh doesn't check for Java versions higher than 17 and notify-send fails silently if the command is not found

### ISSUE THREAD

**Issue by RiQuY** [hyperdefined/CustomLauncherRewrite#99]
**Describe the issue**
The run.sh script only checks for the string "version \"17" in the output of `java -version` command, any other version even higher than 17 fails the check. In the installation docs it that java version 17 or higher should be valid. https://github.com/hyperdefined/CustomLauncherRewrite/wiki/Linux-Install#java-17

After failing the check the run.sh script can fail too because the system may not have the `notify-send` utility.

Output of `java -version` on my system:
```
openjdk version "22.0.1" 2024-04-16
OpenJDK Runtime Environment (build 22.0.1+8-suse-2.1-x8664)
OpenJDK 64-Bit Server VM (build 22.0.1+8-suse-2.1-x8664, mixed mode, sharing)
```

**Log file**
```
/opt/CustomLauncherRewrite/run.sh
/opt/CustomLauncherRewrite/run.sh: línea 24: notify-send: orden no encontrada
```

**Comment by hyperdefined** [comment]
There's already a PR (#96) to fix the Java version check, waiting on the author currently.

For `notify-send` not always being there, I'll see if there's another method for this.

**Comment by hyperdefined** [comment]
Fixed in https://github.com/hyperdefined/CustomLauncherRewrite/commit/1637ecfa85b72e9ad1151c4d4ddf38e1f5d91fd1
